services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=picpay-database'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    networks:
      - picpay-network
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - picpay-network

networks:
  picpay-network: {}

volumes:
  db_data:
